export interface AgentMessage {
  type: 'message';
  text: string;
}

export interface AgentServiceSelection {
  type: 'select_service';
  serviceId: string;
  serviceName: string;
  /** Confirmation text generated by the assistant to send to the customer. */
  text: string;
}

export type AgentResult = AgentMessage | AgentServiceSelection;

export interface AvailableService {
  serviceId: string;
  serviceName: string;
}

export interface GenericAgentPort {
  processMessage(
    openaiToken: string,
    userId: number,
    phone: string,
    messageText: string,
    services: AvailableService[],
    existingThreadId: string | null
  ): Promise<AgentResult>;
}
